#!/bin/bash

set -e

install_go()
{
    # Taken from Google/golang Dockerfile...
    apt-get update -y && apt-get install --no-install-recommends -y -q curl build-essential \
        ca-certificates git mercurial bzr
    mkdir /goroot && curl https://storage.googleapis.com/golang/go1.3.1.linux-amd64.tar.gz | tar xvzf - -C /goroot --strip-components=1
    echo $PWD
    echo "export GOROOT=\"/goroot\"" > ./build/bootstrap.envs
    echo "export PATH=\"$PATH:/goroot/bin\"" >> ./build/bootstrap.envs
}

build_devmapper()
{
    git clone -b v2_02_103 https://git.fedorahosted.org/git/lvm2.git /usr/local/lvm2
    # see https://git.fedorahosted.org/cgit/lvm2.git/refs/tags for release tags

    # Compile and install lvm2
    cd /usr/local/lvm2 \
	&& ./configure --enable-static_link \
	&& make device-mapper \
	&& make install_device-mapper
}

mkdir -p ./build

if [ ! $(command -v go) ]; then
    echo "Going to try installing Go..."
    install_go
fi
if [ ! -d "/usr/local/lvm2" ]; then
    echo "Going to try installing Go..."
    build_devmapper
fi

apt-get update
apt-get install -y uuid-runtime
