#!/bin/bash
set -e

cd $(dirname $0)/..

mkdir -p bin
go build -a -tags "netgo libdm_no_deferred_remove" \
	-ldflags "-X main.VERSION=$VERSION -linkmode external -extldflags -static" \
	--installsuffix netgo -o bin/convoy
