#!/bin/bash

set -e

cd $(dirname $0)/..

. ./scripts/common_functions

set_project_vars

go test -tags "libdm_no_deferred_remove s3test" ./...

result=$(find . -name "*.go" | grep -v ./Godeps | xargs gofmt -s -l)
for i in $result; do
    echo $i
done

[ -n "$result" ] && exit 1

cd tests/integration
py.test -x

echo OK
