#!/bin/bash

set -e

cd $(dirname $0)/..

if [ -x "$(which wrapdocker)" ]; then
    wrapdocker > /tmp/docker.log 2>&1
    docker ps -q
fi

if [ ! -x "$(which net-util.sh)" ]; then
    cp scripts/lib/volmgr_mount /usr/local/bin/volmgr_mount
    chmod +x /usr/local/bin/volmgr_mount
    cp scripts/lib/pdata_tools /usr/local/bin/pdata_tools
    chmod +x /usr/local/bin/pdata_tools
fi

. ./scripts/common_functions

set_project_vars

sudo go test ./...

result=$(find . -name "*.go" | grep -v ./Godeps | xargs gofmt -s -l)
for i in $result; do
    echo $i
done

[ -n "$result" ] && exit 1

echo OK
